#!/bin/bash
#This script allows for update, upgrade, and dist-upgrade
#Author: Stephen J Kennedy
#version 1.4
#DEBUG used with -x (reports shell name, line number, and associated function)
PS4='+ $BASH_SOURCE : $LINENO : ${FUNCNAME[0]} ()'
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

DATE=$(date +"%F")
TIME=$(date +"%H:%M:%S")
PID=$BASHPID
LOG="/var/tmp/${DATE}-${PID}-log"
MAIL=/usr/bin/mail
TO="medicup@gmail.com"

#mail Function uses mail to distribute results of autoUpdate
mailOutput(){
   if [ $? -ne 0 ]
      then
         echo "mail error"
         $MAIL -s "Error with ${HOSTNAME} update: check ${UPDATE}." $TO < $LOG
      else
         echo "Success!"
         $MAIL -s ${DATE}-${HOSTNAME}  $TO < $LOG
   fi
}

#Checks for need to dist-upgrade and
#exits with return 3 if dist-upgrade needed.
autoUpdate (){
   echo "Starting update for $HOSTNAME at $TIME on ${DATE}." > $LOG
   sudo apt-get update
   for UPDATE in upgrade dist-upgrade
   do
      echo "Starting apt-get ${UPDATE}..." >> $LOG
      if [ ${UPDATE} = "dist-upgrade" ]
         then
           apt-get --assume-no $UPDATE || echo "DIST-UPGRADE required" >> $LOG return 3
      else
           apt-get --assume-yes $UPDATE >> $LOG ||  return 1
           echo "apt-get ${UPDATE} successful!" >> $LOG
      fi
   done
}
