#!/bin/bash
#This script allows for update, upgrade, and dist-upgrade
#Author: Stephen J Kennedy
#The file path is in a hidden directory in the /var/log./autoUpdate
#Filename will be the dailyUpdate

HOST=$(hostname -f)
DATE=`date +%m-%d-%y`
TIME=`date +%H:%M:%S`
FINAL=/var/log/.autoUpdate/dailyUpdate
ERR=/var/log/.autoUpdate/.error
MAIL=/usr/sbin/sendmail
TO=medicup@gmail.com
UPDATE="update upgrade dist-upgrade autoremove" #options for autoUpdate do statement

#mail Function uses sendmail to distribute results of autoUpdate when no errors
mailOutput(){
   $MAIL -F admin@${THISHOST} -t $TO < $FINAL
}

#error function is run when there is an error in the update.
#Will distribute an error notification and exit the program
error (){
   echo "${DATE}-${TIME}" > $ERR
   echo "${HOST}-ALERT: There was an error running apt-get ${UPDATE}!" >> $ERR
   $MAIL -F admin@${THISHOST} -t $TO < $ERR
   exit
}

#autoUpdate function uses a do statement that will run until error or
#all update options are processed. It provides a start and success
#response that is exported to a text file
autoUpdate (){
echo "Starting update for $HOSTNAME at $TIME on ${DATE}." > $FINAL
for UPDATE in $UPDATE
do
   echo "Starting apt-get ${UPDATE}..." >> $FINAL
   apt-get --assume-yes $UPDATE || error;
   echo "apt-get ${UPDATE} successful!" >> $FINAL
done
}

autoUpdate;
mailOutput;
exit
