#!/bin/bash
#This script allows for update, upgrade, and dist-upgrade
#Author: Stephen J Kennedy
#The file path is in a hidden directory in the /var/log directory
#Filename will be the hostname.txt

THISHOST=$(hostname -f)
DATE=`date +%m-%d-%y`
TIME=`date +%H:%M:%S`
FILEPATH=/var/log/.autoUpdate
FILENAME=$FILEPATH/${THISHOST}.txt
TO=medicup@gmail.com
SUBJECT="Automated update report from $THISHOST"

mailOutput(){
        sendmail -s $SUBJECT $TO < $FILENAME
}

checkSuccess(){
        if [ $? == 0 ]; then
           echo Succeeded >> $FILENAME
        else
           echo FAILED! >> $FILENAME
        fi
}

#Initiates the auto update, but excludes the output of the console
startAutoUpdate(){
        mkdir -p $FILEPATH;
        echo It is $DATE and the auto update initiated for $THISHOST at $TIME. > $FILENAME
        apt-get update > /dev/null
        checkSuccess;
        echo "" >> $FILENAME
}

#Initiates the upgrade and includes the end results.
startAutoUpgrade(){
        echo Initiating upgrade of $THISHOST >> $FILENAME
        apt-get upgrade -y >> $FILENAME
        checkSuccess;
        echo "" >> $FILENAME
}

#Initiates the dist-upgrade and includes the end results
startAutoDistUpgrade(){
        echo Initiating dist-upgrade of $THISHOST... >> $FILENAME
        apt-get dist-upgrade -y >> $FILENAME
        checkSuccess;
        echo "" >> $FILENAME
        }

startAptGetRemove(){
        echo Initiating apt-get automove of $THISHOST... >> $FILENAME
        apt-get autoremove -y >> $FILENAME
        checkSuccess;
        echo "" $FILENAME
        echo Upgrade of $THISHOST completed at $DATE-$TIME >> $FILENAME
}


startAutoUpdate;
startAutoUpgrade;
startAutoDistUpgrade;
startAptGetRemove;
mailOutput;
